spring.application.name=Api_Inventario
# ==========================================================
# BASE DE DATOS - AIVEN MYSQL
# ==========================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Solo valida la estructura. NO crea ni modifica tablas.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Respeta exactamente nombres como Users, Person, Rol, ProductList...
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ==========================================================
# SERVIDOR: Render proporciona PORT.
# Localmente usa 8080.
# ==========================================================
server.port=${PORT:8080}
# ==========================================================
# JWT
# ==========================================================
security.jwt.secret-key=${JWT_SECRET}

# ==========================================================
# LOGS DE SPRING SECURITY
# ==========================================================
logging.level.org.springframework.security=TRACE